train_file:  '/scratch/work/guoz3/EyeTracking/data/full/new_logs'
image_root: '/home/researcher/Documents/saliency_modeling_issues/UEyes_dataset/images'
eval_image_root: '/home/researcher/Documents/saliency_modeling_issues/UEyes_dataset/images'

bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 64
batch_size_test: 32
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 16
dropout: 0.1


optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}






